language: python
python:
    - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
    - python setup.py develop
    - nosetests --with-coverage --cover-package=cloudshell-networking-devices

after_success:
    - coveralls
