language: python
python:
    - "2.7"

install:
    - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
        pip install -r requirements.txt;
      else
        pip install -r dev_requirements.txt;
      fi'
    - pip install -r test_requirements.txt

script:
    - python setup.py install
    - nosetests --with-coverage --cover-package cloudshell/devices --where=tests

after_success:
    - coveralls
